# theme: minima
title: GregFoote.com
# remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/tactile@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
